// Code generated by "stringer -type TagType -trimprefix TagType"; DO NOT EDIT.

package rls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TagTypeWhitespace-0]
	_ = x[TagTypeDelim-1]
	_ = x[TagTypeText-2]
	_ = x[TagTypePlatform-3]
	_ = x[TagTypeArch-4]
	_ = x[TagTypeSource-5]
	_ = x[TagTypeResolution-6]
	_ = x[TagTypeCollection-7]
	_ = x[TagTypeDate-8]
	_ = x[TagTypeSeries-9]
	_ = x[TagTypeVersion-10]
	_ = x[TagTypeDisc-11]
	_ = x[TagTypeCodec-12]
	_ = x[TagTypeHDR-13]
	_ = x[TagTypeBitDepth-14]
	_ = x[TagTypeAudio-15]
	_ = x[TagTypeChannels-16]
	_ = x[TagTypeOther-17]
	_ = x[TagTypeCut-18]
	_ = x[TagTypeEdition-19]
	_ = x[TagTypeLanguage-20]
	_ = x[TagTypeSize-21]
	_ = x[TagTypeRegion-22]
	_ = x[TagTypeContainer-23]
	_ = x[TagTypeGenre-24]
	_ = x[TagTypeID-25]
	_ = x[TagTypeGroup-26]
	_ = x[TagTypeMeta-27]
	_ = x[TagTypeExt-28]
}

const _TagType_name = "WhitespaceDelimTextPlatformArchSourceResolutionCollectionDateSeriesVersionDiscCodecHDRBitDepthAudioChannelsOtherCutEditionLanguageSizeRegionContainerGenreIDGroupMetaExt"

var _TagType_index = [...]uint8{0, 10, 15, 19, 27, 31, 37, 47, 57, 61, 67, 74, 78, 83, 86, 94, 99, 107, 112, 115, 122, 130, 134, 140, 149, 154, 156, 161, 165, 168}

func (i TagType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TagType_index)-1 {
		return "TagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TagType_name[_TagType_index[idx]:_TagType_index[idx+1]]
}
